  -- Deactivated
  -- Really... I went over them and I dont really think I need those, but will
  -- archive them for now
  --use 'honza/vim-snippets' -- Old vim spinnets engine
  --use 'sjl/gundo.vim' -- Displays buffer history changes
  --use 'tpope/vim-unimpaired' -- Some bracket mapping thing
  --use 'vim-ruby/vim-ruby' -- Vim ruby already supported ruby syntax
  --use 'rodjek/vim-puppet' -- Some puppet language thing
  --use 'Valloric/YouCompleteMe' -- YouCompleteMe was replaced with nvim-cmp
  --use 'Shougo/neosnippet' -- neosnippet was replaced with luasnip
  --use 'Shougo/neosnippet-snippets'
  --use 'pangloss/vim-javascript' -- Adds javascript syntax highlight
  --use 'briancollins/vim-jst' -- Syntax highlight for EJS no longer using
  --use 'ngmy/vim-rubocop' -- Never really used thing
  --use 'danchoi/ri.vim' -- Using <leader>r and <leader>R opens Ruby documentation
  --use 'chrisbra/NrrwRgn' -- TOUSE: type :NR and it will focus visual selection
  --use 'mtscout6/vim-cjsx' -- no longer using CJSX
  --use 'BjRo/vim-extest' -- Executes Exilir tests, deprecated plugin though
  --use 'isRuslan/vim-es6' -- Old highlight syntax for JS
  --use 'wakatime/vim-wakatime' -- Helps track code editing time
  --use 'SirVer/ultisnips' -- replaced with luasnips
  --use 'grvcoelho/vim-javascript-snippets' -- No longer needed snippets
  --use 'ivalkeen/vim-ctrlp-tjump' -- TOUSE: Be able to jump to ctags declarations
  --use 'ervandew/supertab' -- Use tab for all completion suggestions (USE WITH CAUTION)
  --use 'iurifq/ctrlp-rails.vim' -- TOUSE: ctrl-p to jump to rails routes
  --use 'jasoncodes/ctrlp-modified.vim' -- TOUSE: Use ctrl-p to display ONLY modified git-tracked files
  --use 'dhruvasagar/vim-table-mode' -- Allows to edit tables with orgmode
  --use {'nvim-orgmode/orgmode', config = function()
    --require('orgmode').setup{}
  --end
  --use {
    --'folke/which-key.nvim',
    --config = function() require('which-key').setup{} end
  --} -- Displays which-key help
  --use 'sotte/presenting.vim' -- Adds presentations support
  --use 'ryanoasis/vim-devicons' -- Adds icons to files
  --use 'jcarlos7121/vim-colorscheme-icons' -- Adds icons color for devicons
  --use 'ctrlpvim/ctrlp.vim' -- :CtrlP to search files
  --use 'scrooloose/nerdtree' -- Filesearcher File tree
  --use 'flw-cn/vim-nerdtree-l-open-h-close'
  --use 'Xuyuanp/nerdtree-git-plugin' -- Filesearcher Git display for files
